name: github actions test

on:
  workflow_dispatch:

jobs:
  my_job_1:
    name: Job 1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run command
        run: |
          echo $PWD
          ls -al
  my_job_2:
    name: Job 2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run command
        run: |
          echo $PWD
          ls -al
  my_job_3:
    name: Job 3
    needs: [my_job_1, my_job_2]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run command
        run: |
          echo $PWD
          ls -al
